# SPDX-FileCopyrightText: 2021 Forschungs- und Entwicklungszentrum Fachhochschule Kiel GmbH
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI (install, test)
on:
  push:
    branches: master
  pull_request:
    branches:
    - master
    - develop
  workflow_dispatch:

jobs:
  main:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install .
    - name: Run tests
      run: |
        pytest -vv tests
